services:
  postgres:
    image: postgres:16
    container_name: sql_analytics_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_password
      POSTGRES_DB: ecommerce_analytics

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: